version: '3'
services:
  mongodb:
    image: mongo:4.2
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=option123
    ports:
    - 27017:27017
    expose:
    - 27017
    volumes:
    - mongodb-data:/data/db
    command: mongod

volumes:
  mongodb-data: